apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "hdsakhdfsakjhadd"
  annotations:
    github.com/project-slug: dwessendorf/cc-env-hdsakhdfsakjhadd
    backstage.io/techdocs-ref: dir:.# Add this line
spec:
  type: service
  owner: group:guests
  lifecycle: experimental
