site_name: 'hdsakhdfsakjhadd'
site_description: 'Documentation for Confluent Cloud Environment hdsakhdfsakjhadd'

nav:
  - Home: index.md
  - Environment Details: environment-details.md
  - Operations: operations.md

plugins:
  - techdocs-core

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences